### ISSUE TITLE
MLS - Photos Only

### ISSUE THREAD

**Issue by sean8300** [ListerAssister/issues#120]
Needs a workflow for MLS - Photos Only. This will go to MLS - Complete once done. Once implemented we need a training for the editors, MLS & Reps so they know when to use
Submitted By: Chad

**Comment by Juvie92** [comment]
add new row in workflow_step
workflow_id = 5
description: Photos Only
is_problem = 1
code: mls_photos_only

This seems to me like something where directions need to be given to the reps/mls folks on how to utilize this.
I'm thinking something along these lines:
system adds "mls: awaiting photos"
if necessary reps change this to "mls: Photos only" (it will appear under the mls tab in workflow)
then mls changes that to "mls: complete"

I'm not sure how much more this needs.

**Comment by sean8300** [comment]
Made change on live, looks good
