### ISSUE TITLE
Virtual Staging Room Prompt

### ISSUE THREAD

**Issue by sean8300** [ListerAssister/issues#178]
Is it possible to have prompts that ask what rooms the agents want to be virtaully staged when they order 1,2,3,4 etc rooms??
Submitted By: Nicole

**Comment by sean8300** [comment]
This was placed in down the road so think its something we would like to eventually add but not something we have on the table anytime soon

**Comment by Juvie92** [comment]
Not sure if this is still a feature we want to add but I got it to work. 
When ever a number of rooms for virtual staging is selected, that many number of input fields appears for customer to add which rooms to stage.
Doesn't do a validation at the moment. If they leave it blank, it will be marked as 'No Description'.

The room descriptions will be added on to the order item description. So something like "Virtual Room 2 (Kitchen, Livingroom)"
