### ISSUE TITLE
Refund through the system and reflection of refunds

### ISSUE THREAD

**Issue by sean8300** [ListerAssister/issues#186]
Just a few ideas I had in mind about our system and how things could be simplified moving forward. One issue is that no refunds are reflected anywhere when they are done through authorize.net.  When agents pull up their account history or even I pull it from LA, no refunds are reflected in totals. I see this becoming a hassle.  I think if we could find a way to process refunds or (credits) through the system just like we have the add-on charge button then we would be able to have the refund actually reflected as a transaction. Reps would see I processed the refund and agents would see the change on their totals when viewing their history online. 
Submitted By: Meghan

**Comment by sean8300** [comment]
Im not sure returning money through the dashboard is something Chad would want to do.  Asking Chad if this is something we should pursue

**Comment by sean8300** [comment]
Slacked Chad:
I have an old ticket from Meghan asking about processing refunds through the dashboard.  Is this (giving money to customers) something we would ever want done in the dashboard?

**Comment by sean8300** [comment]
Response from Chad:
I think she's asking for the dashboard to be able to show refunds so they have the correct amount

**Comment by sean8300** [comment]
Nicole had a ticket that was very similar to this, bringing her in on this one and closed hers out

**Comment by Juvie92** [comment]
This is similar to ticket #697 which has already been addressed and closed so doing the same to this.
