### ISSUE TITLE
Twilight on scheduling screen for California is not accurate.

### ISSUE THREAD

**Issue by sean8300** [ListerAssister/issues#272]
Because of daylight savings twilight is now an hour earlier than the routing screen is displaying. 
Submitted By: Kate

**Comment by sean8300** [comment]
This is actually a bit of a deal, the order form would have to start pulling in twilight times based on the zip entered, which its not even close to doing right now

**Comment by Juvie92** [comment]
Seems the issue dealt with how javascript was formatting the timestamp under a local timezone. Switched it so timestamp is formatted in php under the timezone of storage location (requires new column in database).
