### ISSUE TITLE
No location fee

### ISSUE THREAD

**Issue by sean8300** [ListerAssister/issues#296]
Please look at this order - Zip code should have a location charge, but nothing was charged. Thank you.
Submitted By: Nicole

**Comment by sean8300** [comment]
This is an old ticket, dont think this is a frequent issue, think this is just a one off.

**Comment by Juvie92** [comment]
As this is an old ticket, I'm assuming relevant info for this has been forgotten but going to check with Nicole and see if there has been any other issues similar to this. If nothing, going to close this.

**Comment by Juvie92** [comment]
No info available to investigate this further and no similar issues that Nicole is aware of.
Closing this ticket.
